version: "3.9"
services:
  order-db:
    image: postgres:16
    container_name: order_postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5445:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

volumes:
  order_pgdata:
